# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(630, 433)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        MainWindow.setPalette(palette)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 340, 601, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveSettingsButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.saveSettingsButton.setObjectName("saveSettingsButton")
        self.horizontalLayout_3.addWidget(self.saveSettingsButton)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.loadSettingsButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.loadSettingsButton.setObjectName("loadSettingsButton")
        self.horizontalLayout_3.addWidget(self.loadSettingsButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.engineKillerButton = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.engineKillerButton.setText("")
        self.engineKillerButton.setObjectName("engineKillerButton")
        self.horizontalLayout_2.addWidget(self.engineKillerButton)
        self.engineKillerLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.engineKillerLabel.setObjectName("engineKillerLabel")
        self.horizontalLayout_2.addWidget(self.engineKillerLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.startButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_2.addWidget(self.startButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 541, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab_1)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 511, 261))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.engineSettings = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.engineSettings.setContentsMargins(0, 0, 0, 0)
        self.engineSettings.setObjectName("engineSettings")
        self.settingsContainer = QtWidgets.QVBoxLayout()
        self.settingsContainer.setObjectName("settingsContainer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.threadsLabel = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.threadsLabel.setObjectName("threadsLabel")
        self.horizontalLayout_5.addWidget(self.threadsLabel)
        self.threads = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.threads.setObjectName("threads")
        self.horizontalLayout_5.addWidget(self.threads)
        self.settingsContainer.addLayout(self.horizontalLayout_5)
        self.threadsSlider = QtWidgets.QSlider(self.verticalLayoutWidget_6)
        self.threadsSlider.setMinimum(1)
        self.threadsSlider.setMaximum(12)
        self.threadsSlider.setPageStep(1)
        self.threadsSlider.setProperty("value", 4)
        self.threadsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.threadsSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.threadsSlider.setTickInterval(1)
        self.threadsSlider.setObjectName("threadsSlider")
        self.settingsContainer.addWidget(self.threadsSlider)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.skillLevelLabel = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.skillLevelLabel.setObjectName("skillLevelLabel")
        self.horizontalLayout.addWidget(self.skillLevelLabel)
        self.skillLevel = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.skillLevel.setObjectName("skillLevel")
        self.horizontalLayout.addWidget(self.skillLevel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.skillSlider = QtWidgets.QSlider(self.verticalLayoutWidget_6)
        self.skillSlider.setMinimum(1)
        self.skillSlider.setMaximum(20)
        self.skillSlider.setPageStep(1)
        self.skillSlider.setSliderPosition(5)
        self.skillSlider.setOrientation(QtCore.Qt.Horizontal)
        self.skillSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.skillSlider.setTickInterval(1)
        self.skillSlider.setObjectName("skillSlider")
        self.verticalLayout_2.addWidget(self.skillSlider)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.minDepthLabel = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.minDepthLabel.setObjectName("minDepthLabel")
        self.horizontalLayout_4.addWidget(self.minDepthLabel)
        self.depth = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.depth.setObjectName("depth")
        self.horizontalLayout_4.addWidget(self.depth)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.minDepthSlider = QtWidgets.QSlider(self.verticalLayoutWidget_6)
        self.minDepthSlider.setMinimum(1)
        self.minDepthSlider.setMaximum(20)
        self.minDepthSlider.setPageStep(1)
        self.minDepthSlider.setProperty("value", 5)
        self.minDepthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.minDepthSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.minDepthSlider.setTickInterval(1)
        self.minDepthSlider.setObjectName("minDepthSlider")
        self.verticalLayout.addWidget(self.minDepthSlider)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.hashLabel = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.hashLabel.setObjectName("hashLabel")
        self.horizontalLayout_7.addWidget(self.hashLabel)
        self.hashsize = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.hashsize.setObjectName("hashsize")
        self.horizontalLayout_7.addWidget(self.hashsize)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.hashSlider = QtWidgets.QSlider(self.verticalLayoutWidget_6)
        self.hashSlider.setMinimum(256)
        self.hashSlider.setMaximum(4096)
        self.hashSlider.setSingleStep(256)
        self.hashSlider.setPageStep(256)
        self.hashSlider.setProperty("value", 256)
        self.hashSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hashSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hashSlider.setTickInterval(256)
        self.hashSlider.setObjectName("hashSlider")
        self.verticalLayout_5.addWidget(self.hashSlider)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.settingsContainer.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.contemptLabel = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.contemptLabel.setObjectName("contemptLabel")
        self.horizontalLayout_6.addWidget(self.contemptLabel)
        self.contempt = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.contempt.setObjectName("contempt")
        self.horizontalLayout_6.addWidget(self.contempt)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.contemptSlider = QtWidgets.QSlider(self.verticalLayoutWidget_6)
        self.contemptSlider.setMinimum(0)
        self.contemptSlider.setMaximum(300)
        self.contemptSlider.setSingleStep(25)
        self.contemptSlider.setPageStep(25)
        self.contemptSlider.setProperty("value", 50)
        self.contemptSlider.setOrientation(QtCore.Qt.Horizontal)
        self.contemptSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.contemptSlider.setTickInterval(25)
        self.contemptSlider.setObjectName("contemptSlider")
        self.verticalLayout_4.addWidget(self.contemptSlider)
        self.settingsContainer.addLayout(self.verticalLayout_4)
        self.engineSettings.addLayout(self.settingsContainer)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 521, 261))
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setRowCount(6)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(103)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(42)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(20)
        self.tabWidget.addTab(self.tab_4, "")
        self.evalBar = QtWidgets.QProgressBar(self.centralwidget)
        self.evalBar.setEnabled(True)
        self.evalBar.setGeometry(QtCore.QRect(580, 60, 31, 256))
        self.evalBar.setMinimumSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.evalBar.setPalette(palette)
        self.evalBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.evalBar.setAutoFillBackground(False)
        self.evalBar.setProperty("value", 50)
        self.evalBar.setAlignment(QtCore.Qt.AlignCenter)
        self.evalBar.setTextVisible(True)
        self.evalBar.setOrientation(QtCore.Qt.Vertical)
        self.evalBar.setInvertedAppearance(False)
        self.evalBar.setFormat("")
        self.evalBar.setObjectName("evalBar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(580, 40, 31, 16))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 630, 22))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.skillSlider.valueChanged['int'].connect(self.skillLevel.setNum)
        self.minDepthSlider.valueChanged['int'].connect(self.depth.setNum)
        self.threadsSlider.valueChanged['int'].connect(self.threads.setNum)
        self.contemptSlider.valueChanged['int'].connect(self.contempt.setNum)
        self.hashSlider.valueChanged['int'].connect(self.hashsize.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.saveSettingsButton.clicked.connect(self.writeSettings)
        self.loadSettingsButton.clicked.connect(self.readSettings)
        self.engineKillerButton.clicked.connect(self.engineKiller)
        self.startButton.clicked.connect(self.startBot)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chess Bot"))
        self.saveSettingsButton.setText(_translate("MainWindow", "Save Settings"))
        self.loadSettingsButton.setText(_translate("MainWindow", "Load Settings"))
        self.engineKillerLabel.setText(_translate("MainWindow", "Engine Killer Mode"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.threadsLabel.setText(_translate("MainWindow", "Threads: "))
        self.threads.setText(_translate("MainWindow", "4"))
        self.skillLevelLabel.setText(_translate("MainWindow", "Skill Level: "))
        self.skillLevel.setText(_translate("MainWindow", "5"))
        self.minDepthLabel.setText(_translate("MainWindow", "Minimum Depth:"))
        self.depth.setText(_translate("MainWindow", "5"))
        self.hashLabel.setText(_translate("MainWindow", "Hash Size:"))
        self.hashsize.setText(_translate("MainWindow", "256"))
        self.contemptLabel.setText(_translate("MainWindow", "Contempt:"))
        self.contempt.setText(_translate("MainWindow", "50"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Engine Settings"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Turn Start"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Turn End"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "Depth"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "Skill"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "Time / Move"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Turn Settings"))
        self.label.setText(_translate("MainWindow", "0.00"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))

    def writeSettings(self):
        f = open('settings.txt', 'w')
        f.write(self.threads.text() + '\n')
        f.write(self.skillLevel.text() + '\n')
        f.write(self.depth.text() + '\n')
        f.write(self.hashsize.text() + '\n')
        f.write(self.contempt.text() + '\n')
        for i in range(1,6):
            for j in range(0,5):
                if self.tableWidget.item(i,j) is None:
                    f.write(str(i) + ' ' + str(j) + ' -1\n')
                else:
                    f.write(str(i) + ' ' + str(j) + ' ')
                    f.write(self.tableWidget.item(i,j).text() + '\n')
        f.close()

    def readSettings(self):
        f = open('settings.txt', 'r')
        self.threadsSlider.setValue(int(f.readline()))
        self.skillSlider.setValue(int(f.readline()))
        self.minDepthSlider.setValue(int(f.readline()))
        self.hashSlider.setValue(int(f.readline()))
        self.contemptSlider.setValue(int(f.readline()))
        line = f.readline()
        while line != '':
            i,j,v = line.split(' ')
            v = v.replace('\n', '')
            if v == '-1':
                v = ''
            self.tableWidget.setItem(int(i),int(j), QtWidgets.QTableWidgetItem(v))

            #if self.tableWidget.item(int(i), int(j)) is None:
            #    item = QtWidgets.QTableWidgetItem(v)
            #    self.tableWidget.setItem(int(i), int(j), item)
            #else:
            #    self.tableWidget.item(int(i), int(j)).setText(v);
            line = f.readline()
        f.close()

    def engineKiller(self):
        if self.engineKillerButton.isChecked():
            self.writeSettings()
            self.threadsSlider.setValue(8)
            self.skillSlider.setValue(20)
            self.minDepthSlider.setValue(18)
            self.hashSlider.setValue(4096)
            self.contemptSlider.setValue(0)
            self.tableWidget.setItem(1,0,QtWidgets.QTableWidgetItem('0'))
            self.tableWidget.setItem(1,1,QtWidgets.QTableWidgetItem('200'))
            self.tableWidget.setItem(1,2,QtWidgets.QTableWidgetItem('18'))
            self.tableWidget.setItem(1,3,QtWidgets.QTableWidgetItem('20'))
            self.tableWidget.setItem(1,4,QtWidgets.QTableWidgetItem('250'))
            for i in range(2,6):
                for j in range(0,6):
                    self.tableWidget.setItem(i,j,QtWidgets.QTableWidgetItem(''))
        else:
            self.readSettings()

    def startBot(self):
        if self.startButton.text() == 'Start':
            #run the bot
            self.startButton.setText('Stop')
        else:
            #stop the bot
            self.startButton.setText('Start')




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
